/**
 * Grandes villes françaises (top ~80 par population/poids touristique).
 * Pour ces villes, on tente **Unsplash en premier** (photos contemporaines, mieux
 * cadrées pour un header de fiche) avant de basculer sur Wikipedia + Pexels.
 * Slugs = résultat de slugFromNom (minuscules, accents supprimés, tirets).
 */
const MAJOR_FR_CITY_SLUGS = new Set<string>([
  "paris",
  "marseille",
  "lyon",
  "toulouse",
  "nice",
  "nantes",
  "strasbourg",
  "montpellier",
  "bordeaux",
  "lille",
  "rennes",
  "reims",
  "saint-etienne",
  "toulon",
  "le-havre",
  "grenoble",
  "dijon",
  "angers",
  "nimes",
  "villeurbanne",
  "aix-en-provence",
  "brest",
  "clermont-ferrand",
  "limoges",
  "tours",
  "amiens",
  "perpignan",
  "metz",
  "besancon",
  "orleans",
  "rouen",
  "mulhouse",
  "caen",
  "nancy",
  "argenteuil",
  "saint-denis",
  "montreuil",
  "roubaix",
  "dunkerque",
  "tourcoing",
  "avignon",
  "nanterre",
  "creteil",
  "vitry-sur-seine",
  "poitiers",
  "versailles",
  "courbevoie",
  "colombes",
  "pau",
  "la-rochelle",
  "calais",
  "cannes",
  "antibes",
  "saint-malo",
  "biarritz",
  "chamonix",
  "chamonix-mont-blanc",
  "annecy",
  "chambery",
  "bayonne",
  "perigueux",
  "arcachon",
  "carcassonne",
  "quimper",
  "vannes",
  "saint-tropez",
  "ajaccio",
  "bastia",
  "calvi",
  "bonifacio",
  "deauville",
  "honfleur",
  "etretat",
  "mont-saint-michel",
  "saint-emilion",
  "sarlat",
  "sarlat-la-caneda",
  "colmar",
  "riquewihr",
  "eguisheim",
  "angouleme",
  "blois",
  "amboise",
  "tours",
  "chartres",
  "bourges",
  "albi",
  "rocamadour",
]);

export function isMajorFrenchCitySlug(slug: string): boolean {
  const s = (slug || "").trim().toLowerCase();
  if (!s) return false;
  return MAJOR_FR_CITY_SLUGS.has(s);
}
